# Generated by Django 3.2 on 2021-06-11 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=255)),
                ('student_age', models.IntegerField(default=0)),
                ('mobile_number', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.myclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.myclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
    ]
