# Generated by Django 3.2 on 2021-06-11 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, upload_to='media/')),
                ('subject', models.CharField(max_length=255)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.myclass')),
            ],
        ),
    ]
