# Generated by Django 3.2 on 2021-06-11 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=10)),
                ('sub1', models.CharField(max_length=50)),
                ('sub2', models.CharField(max_length=50)),
                ('sub3', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('video', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.myclass')),
            ],
        ),
    ]
